apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-mongo
  template:
    metadata:
      labels:
        app: product-mongo
    spec:
      containers:
      - name: mongodb
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-product-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-product-secret
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: product-mongo-svc
spec:
  selector:
    app: product-mongo  
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  type: ClusterIP
---

## PRODUCT MONGO SECRET AND CONFIGMAP
apiVersion: v1
kind: Secret
metadata:
  name: mongo-product-secret
type: Opaque
data:
  # username: admin (base64 encoded)
  username: YWRtaW4=
  # password: admin (base64 encoded)
  password: YWRtaW4=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-product-config
data:
  MONGO_HOST: product-mongo-svc
  MONGO_PORT: "27017"