apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0
        ports:
        - containerPort: 9092
        env:
        # Kafka broker config
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-svc:2181"
        # Listeners - internal cluster communication
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-svc:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        # Log retention
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "168" # 7 days
        - name: KAFKA_LOG_RETENTION_BYTES
          value: "1073741824" # 1GB
        # Auto create topics
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        # Number of partitions per topic (default)
        - name: KAFKA_NUM_PARTITIONS
          value: "3"
        # Replication factor (must be <= number of brokers)
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "1"
        # Offsets topic replication
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        # Transaction state log replication
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        # Min in-sync replicas
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  selector:
    app: kafka
  ports:
  - name: broker
    port: 9092
    targetPort: 9092
  type: ClusterIP

