apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  # Enable TLS so you can access https://ecommerce.local and set Secure cookies
  tls:
    - hosts:
        - ecommerce.local
      secretName: ecommerce-local-tls # Cert for ecommerce.local
    - hosts:
        - admin.ecommerce.local
      secretName: admin-ecommerce-local-tls # Cert for admin.ecommerce.local
  ingressClassName: nginx
  rules:
  - host: ecommerce.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-svc
            port:
              number: 3000
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 3000
      - path: /api/admin
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 3000
      - path: /api/products
        pathType: Prefix
        backend:
          service:
            name: product-svc
            port:
              number: 3000
      - path: /api/cart
        pathType: Prefix
        backend:
          service:
            name: cart-svc
            port:
              number: 3000
      - path: /api/orders
        pathType: Prefix
        backend:
          service:
            name: order-svc
            port:
              number: 3000
      - path: /api/payments
        pathType: Prefix
        backend:
          service:
            name: payment-svc
            port:
              number: 3000
      - path: /ws/notifications
        pathType: Prefix
        backend:
          service:
            name: notifications-svc
            port:
              number: 3000
  - host: admin.ecommerce.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin-svc
            port:
              number: 3000
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 3000
      - path: /api/admin
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 3000
      - path: /api/orders
        pathType: Prefix
        backend:
          service:
            name: order-svc
            port:
              number: 3000
      - path: /api/products
        pathType: Prefix
        backend:
          service:
            name: product-svc
            port:
              number: 3000
      - path: /api/payments
        pathType: Prefix
        backend:
          service:
            name: payment-svc
            port:
              number: 3000
  
 
