apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - minio.local
      secretName: minio-local-tls
    - hosts:
        - minio-api.local
      secretName: minio-api-local-tls
  ingressClassName: nginx
  rules:
  # MinIO Console (Web UI)
  - host: minio.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9001
  # MinIO API (S3-compatible for images)
  - host: minio-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9000
